version: "3"

services:
  discovery-server:
    container_name: discovery-server
    image: ishahanduja/servicediscovery-image:v2-release
    ports:
      - "8888:8888"

  api-gateway:
    container_name: api-gateway
    image: ishahanduja/apigateway-image:v1-release
    ports:
      - "9000:9000"
    links:
      - discovery-server:discovery-server
    environment:
      - discovery_server_url=http://localhost:8888/eureka

  login-application:
    container_name: login-application
    image: ishahanduja/loginapp-image:v1-release
    ports:
      - "9001:9001"
    links:
      - discovery-server:discovery-server
    environment:
      - discovery_server_url=http://localhost:8888/eureka

  flight-search:
    container_name: flight-search
    image: ishahanduja/flightsearch-image:v1-release
    ports:
      - "9002:9002"
    links:
      - discovery-server:discovery-server
    environment:
      - discovery_server_url=http://localhost:8888/eureka

  hotel-search:
    container_name: hotel-search
    image: ishahanduja/hotelsearch-image:v1-release
    ports:
      - "9003:9003"
    links:
      - discovery-server:discovery-server
    environment:
      - discovery_server_url=http://localhost:8888/eureka

  booking-service:
    container_name: booking-service
    image: ishahanduja/bookingservice-image:v1-release
    ports:
      - "9004:9004"
    links:
      - discovery-server:discovery-server
    environment:
      - discovery_server_url=http://localhost:8888/eureka



